import { Icons } from './icons/Icons';
import { IconsCommunication } from './icons/IconsCommunication';
import { IconsActions } from './icons/IconsActions';
import { NeutralColors } from './colors/Colors';

export const nestedListItems = [
  {
    id: '1',
    label: 'Para mim',
    items: [
      { id: '1-2', 
        icon: <Icons.homeSimpleBar width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Meus Endereços', 
        path: 'UserAddressesView',
      },
      { id: '1-3', 
        icon: <IconsCommunication.notification width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Notificações', 
        path: 'UserNotificationsView',
      },
      // { id: '1-4', 
      //   icon: <Icons.barcode width={16} height={16} />, 
      //   label: 'Seguindo', 
      //   path: 'UserFollowingView',
      // },
      // { id: '1-5', 
      //   icon: <Icons.barcode width={16} height={16} />, 
      //   label: 'Seguidores', 
      //   path: 'UserFollowersView',
      // },
      { id: '1-6', 
        icon: <Icons.history width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Histórico', 
        path: 'UserHistoryView',
      },
      { id: '1-7', 
        icon: <Icons.ticket width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Cupons', 
        path: 'UserCouponsView',
      },
      { id: '1-8', 
        icon: <Icons.shoppingBag width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Minhas Compras', 
        path: 'UserPurchasesView',
      },
      { id: '1-9', 
        icon: <Icons.creditCard width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Meus Cartões', 
        path: 'UserCardsView',
      },
      { id: '1-10', 
        icon: <Icons.badgeEmpty width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Minhas Insígnias', 
        path: 'UserBadgesView',
      },
    ]
  },
  {
    id: '2',
    label: 'Para minha loja',
    items: [
      { id: '2-1', 
        icon: <Icons.store width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Criar minha loja', 
        path: 'CreateStoreView',
      },
      { id: '2-2', 
        icon: <Icons.bag width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Parceiros', 
        path: 'PartnersView',
      },
      { id: '2-3', 
        icon: <Icons.barcode width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Faturamento', 
        path: 'BillingView',
      },
      { id: '2-4', 
        icon: <Icons.barcode width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Selo oficial', 
        path: 'OfficialSealView',
      },
    ]
  },
  {
    id: '3',
    label: 'Outros',
    items: [
      { id: '3-1', 
        icon: <Icons.headset width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Ajuda e FAQ', 
        path: 'HelpAndFAQView',
      },
      { id: '3-2', 
        icon: <Icons.lock width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Privacidade', 
        path: 'PrivacyView',
      },
      { id: '3-3', 
        icon: <IconsCommunication.documentText width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Termos e Condições', 
        path: 'TermsAndConditionsView',
      },
      { id: '3-4', 
        icon: <IconsActions.infoCircle width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Sobre a MyBoxy', 
        path: 'AboutMyBoxyView',
      },
    ]
  },
];