import { v4 as uuidv4 } from 'uuid';

import { Icons } from './icons/Icons';
import { IconsCommunication } from './icons/IconsCommunication';
import { IconsActions } from './icons/IconsActions';
import { NeutralColors } from './colors/Colors';

const newId = uuidv4();

export const nestedListItems = [
  {
    id: uuidv4(),
    label: 'Para mim',
    items: [
      { id: uuidv4(), 
        icon: <Icons.homeSimpleBar width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Meus Endereços', 
        path: 'UserAddressesView',
      },
      { id: uuidv4(), 
        icon: <Icons.wallet width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Minha Carteira', 
        path: 'UserWalletView',
      },
      { id: uuidv4(), 
        icon: <IconsCommunication.notification width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Notificações', 
        path: 'UserNotificationsView',
      },
      { id: uuidv4(), 
        icon: <IconsActions.checkboxSquareRounded width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Permissões', 
        path: 'UserPermissionsView',
      },
      // { id: '1-5', 
      //   icon: <Icons.barcode width={16} height={16} />, 
      //   label: 'Seguidores', 
      //   path: 'UserFollowersView',
      // },
      { id: uuidv4(), 
        icon: <Icons.history width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Histórico', 
        path: 'UserHistoryView',
      },
      { id: uuidv4(), 
        icon: <Icons.ticket width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Cupons', 
        path: 'UserCouponsView',
      },
      { id: uuidv4(), 
        icon: <Icons.shoppingBag width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Minhas Compras', 
        path: 'UserPurchasesView',
      },
      { id: uuidv4(), 
        icon: <Icons.creditCard width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Meus Cartões', 
        path: 'UserCardsView',
      },
      { id: uuidv4(), 
        icon: <Icons.badgeEmpty width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Minhas Insígnias', 
        path: 'UserBadgesView',
      },
    ]
  },
  {
    id: uuidv4(),
    label: 'Para minha loja',
    items: [
      { id: uuidv4(), 
        icon: <Icons.store width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Criar minha loja', 
        path: 'CreateStoreView',
      },
      { id: uuidv4(), 
        icon: <Icons.bag width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Parceiros', 
        path: 'PartnersView',
      },
      { id: uuidv4(), 
        icon: <Icons.barcode width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Faturamento', 
        path: 'BillingView',
      },
      { id: uuidv4(), 
        icon: <Icons.barcode width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Selo oficial', 
        path: 'OfficialSealView',
      },
    ]
  },
  {
    id: uuidv4(),
    label: 'Outros',
    items: [
      { id: uuidv4(), 
        icon: <Icons.headset width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Ajuda e FAQ', 
        path: 'HelpAndFAQView',
      },
      { id: uuidv4(), 
        icon: <Icons.lock width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Privacidade', 
        path: 'PrivacyView',
      },
      { id: uuidv4(), 
        icon: <IconsCommunication.documentText width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Termos e Condições', 
        path: 'TermsAndConditionsView',
      },
      { id: uuidv4(), 
        icon: <IconsActions.infoCircle width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Sobre a MyBoxy', 
        path: 'AboutMyBoxyView',
      },
      { id: uuidv4(), 
        icon: <IconsActions.userDelete width={16} height={16} strokeColor={NeutralColors.textSecondary} />, 
        label: 'Excluir conta', 
        path: 'DeleteAccountView',
      },
    ]
  },
];