import { Icons } from './constants/Icons';

export const nestedListItems = [
  {
    id: '1',
    label: 'Para mim',
    items: [
      { id: '1-1', 
        icon: <Icons.user width={16} height={16} />, 
        label: 'Meus Dados', 
        path: 'UserProfileView',
      },
      { id: '1-2', 
        icon: <Icons.bag width={16} height={16} />, 
        label: 'Endereços', 
        path: 'UserAddressesView',
      },
      { id: '1-3', 
        icon: <Icons.barcode width={16} height={16} />, 
        label: 'Notificações', 
        path: 'UserNotificationsView',
      },
      { id: '1-4', 
        icon: <Icons.barcode width={16} height={16} />, 
        label: 'Seguindo', 
        path: 'UserFollowingView',
      },
      { id: '1-5', 
        icon: <Icons.barcode width={16} height={16} />, 
        label: 'Seguidores', 
        path: 'UserFollowersView',
      },
      { id: '1-6', 
        icon: <Icons.barcode width={16} height={16} />, 
        label: 'Histórico', 
        path: 'UserHistoryView',
      },
      { id: '1-7', 
        icon: <Icons.barcode width={16} height={16} />, 
        label: 'Cupons', 
        path: 'UserCouponsView',
      },
      { id: '1-8', 
        icon: <Icons.barcode width={16} height={16} />, 
        label: 'Minhas Compras', 
        path: 'UserPurchasesView',
      },
      { id: '1-9', 
        icon: <Icons.barcode width={16} height={16} />, 
        label: 'Minhas Insígnias', 
        path: 'UserBadgesView',
      },
    ]
  },
  {
    id: '2',
    label: 'Para minha loja',
    items: [
      { id: '2-1', 
        icon: <Icons.user width={16} height={16} />, 
        label: 'Criar minha loja', 
        path: 'CreateStoreView',
      },
      { id: '2-2', 
        icon: <Icons.bag width={16} height={16} />, 
        label: 'Parceiros', 
        path: 'PartnersView',
      },
      { id: '2-3', 
        icon: <Icons.barcode width={16} height={16} />, 
        label: 'Faturamento', 
        path: 'BillingView',
      },
      { id: '2-4', 
        icon: <Icons.barcode width={16} height={16} />, 
        label: 'Selo oficial', 
        path: 'OfficialSealView',
      },
    ]
  },
  {
    id: '3',
    label: 'Mais configurações',
    items: [
      { id: '3-1', 
        icon: <Icons.user width={16} height={16} />, 
        label: 'Buscas salvas', 
        path: 'SavedSearchesView',
      },
      { id: '3-2', 
        icon: <Icons.bag width={16} height={16} />, 
        label: 'Privacidade', 
        path: 'PrivacyView',
      },
      { id: '3-3', 
        icon: <Icons.barcode width={16} height={16} />, 
        label: 'Termos e Condições', 
        path: 'TermsAndConditionsView',
      },
      { id: '3-4', 
        icon: <Icons.barcode width={16} height={16} />, 
        label: 'Sobre a MyBoxy', 
        path: 'AboutMyBoxyView',
      },
    ]
  },
];